### ISSUE TITLE
Models are named after their parameters. This is unwieldly, long, and doesn't scale well.

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#11]
We still want an easy way to determine what parameters were used in a model's creation. 

Putting them all into the file name runs the following risks:

- [x] File name could exceed windows required file lengths
- [x] File name is hard to read due to no separation character

**Comment by stevk** [comment]
I think the solution to this is to:

- [ ] List the attributes used in the "asset" portion of the file, along with the generator and version.
- [ ] Name the file using a combination of the test name and the number of files created.

**Comment by kcoley** [comment]
+1 on including the data within the glTF file, which can work in asset portion. 

Another idea would be to group the glTF files into subdirectories and include a text file in the root directory referring to which parameters are in which folder, if that can help with querying.
