### ISSUE TITLE
Convert.ToByte chokes on -1, except for with Tangent Coords

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#113]
Looks like Convert.ToByte is having an issue dealing with negative numbers

**Comment by kcoley** [comment]
Hmm, this is an input problem, since it expects unsigned bytes.  Is this happening with the tangent coords?

**Comment by stevk** [comment]
This is with the texCoords. I'll change the values to not include negative numbers.

**Comment by stevk** [comment]
Updated the title. For some reason tangent cords work with a negative number. I also noticed that the bin size is the same between models using float, byte, and ushort. I suspect that the float isn't actually being converted for Tangent. (repro with branch stevk/primattributes2)

**Comment by kcoley** [comment]
I'll look into this

**Comment by kcoley** [comment]
Not found in spec, so closing out.
