### ISSUE TITLE
Model 9 (TexCoord0_SHORT - TexCoord1_SHORT) for PrimitiveAttributes does not load in Babylon.js

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#130]
Model 9 doesn't load in Babylon.js

It is TexCoord0_SHORT - TexCoord1_SHORT

[Sample.zip](https://github.com/bghgary/glTF-Asset-Generator/files/1319164/Sample.zip)

**Comment by kcoley** [comment]
I think short and byte are currently not supported in BabylonJS. 

@bghgary , should we report these issues here or on the BabylonJS Github page?

**Comment by stevk** [comment]
Model 7 has the same issue and is the same other than using byte.

**Comment by bghgary** [comment]
I say report it on Babylon.js forum, but let's collect all the issues before doing so.
