### ISSUE TITLE
Models in Primitive_Attributes test look like they have stretched/broke textures

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#160]
We were using a special UV mapping to show when multiple textures were applied. We don't need this anymore since different images are being used for the textures. Use a 1:1 mapping and verify that there are visual differences with two textures being applied at once.

**Comment by stevk** [comment]
I think Tangent is making the textures do this. I'll need assistance finding a better value of tangent to use (assuming that is the solution).

**Comment by kcoley** [comment]
This is due to a bug in writing Tangents to the buffer.  PR is here #165

**Comment by kcoley** [comment]
PR has been merged.
