### ISSUE TITLE
Wrapper is missing some properties for materials

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#18]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-material 

Missing:
- [ ] name 
- [ ] alphaCutoff
- [ ] doubleSided

I also see that there is a normalScale property implemented, but I don't see it in the glTF spec.

**Comment by kcoley** [comment]
Thanks for flagging these.  I'll add them in to the GLTFMaterial class.

**Comment by kcoley** [comment]
The scale for the normal texture is defined within the normalTextureInfo in the spec:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-normaltextureinfo

**Comment by stevk** [comment]
Ah ok. I think I understand then.

**Comment by kcoley** [comment]
PR created #20

**Comment by kcoley** [comment]
Merged
