### ISSUE TITLE
GLTFMaterial.emissiveFactor is using Vector4 instead of Vector3

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#19]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-material

Required type for emissiveFactor is number [3] per the spec, but it is being declared as Vector4 

This will need to be corrected on at least line 593 and 692 of GLTFWrapper.cs

**Comment by kcoley** [comment]
PR created #20

**Comment by kcoley** [comment]
Merged
