### ISSUE TITLE
A set primitive mode is reset to TRIANGLES by the Runtime layer.

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#207]

**Comment by stevk** [comment]
I think this occurs at line 209 of MeshPrimitive.cs (Or at least this is about the point that the data is lost).
`glTFLoader.Schema.MeshPrimitive mPrimitive = new glTFLoader.Schema.MeshPrimitive();`

Use branch `stevk/primitive` to reproduce the issue.

**Comment by kcoley** [comment]
I don't think I actually use the Mode property when generating the glTF Schema MeshPrimitive.  Should be quick to fix this.

**Comment by kcoley** [comment]
Fix should now be in develop #208
