### ISSUE TITLE
Wrapper GLTFTexture missing definition for name

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#22]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-texture

I think the GLTFTexture class is missing a definition for name.

**Comment by kcoley** [comment]
Ah, yes.  I'll fix this.  I'll also do a re-audit of the other wrapper types.

**Comment by kcoley** [comment]
PR created #23 , which includes this fix and other missing types.

**Comment by kcoley** [comment]
Merged
