### ISSUE TITLE
sampler and source in GLTFTexture are being treated as required attributes by the wrapper

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#24]
Encountering an error when creating an object that does not have a defined sampler and/or source.

System.NullReferenceException: 'Object reference not set to an instance of an object.'

Use the  stevk/mattextures brance to reproduce this issue.

**Comment by kcoley** [comment]
Taking a look.

**Comment by kcoley** [comment]
So it looks like the wrapper assumes the sampler is already defined when using a texture on a material.  I'll change the behavior where it won't use a sampler if it does not exist.

**Comment by kcoley** [comment]
Going to work on this as a separate PR since it might involve a little more code tweaking

**Comment by stevk** [comment]
That is fine with me. I'm making local commits to my local copy of the 'stevk/mattextures' branch but I'll leave the code on the server in place so you have an easy repro.

**Comment by kcoley** [comment]
Sounds good, thanks!

**Comment by kcoley** [comment]
PR created #25

**Comment by kcoley** [comment]
Merged
