### ISSUE TITLE
Indices Component Type is not being respected if not int

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#249]
Use branch `stevk/mesh` on my fork to test for this issue. The bin sizes for models 06, 07, and 08 are the same even though they should be using different indices component types.

My best guess is that line 314 of MeshPrimitive is writing the indices as a uint, instead of using the set component type. The component type looks correct up until that line.

```
glTFLoader.Schema.Accessor accessor = CreateAccessor(bufferviewIndex, 0, indexComponentType, Indices.Count(), "Indices Accessor", null, null, glTFLoader.Schema.Accessor.TypeEnum.SCALAR, null);
                accessors.Add(accessor);
                foreach(var index in Indices)
                {
                    geometryData.Writer.Write((uint)index);
                }
```

**Comment by kcoley** [comment]
That's a line I forgot to change.  I'll make the fix.

**Comment by kcoley** [comment]
PR created #251

**Comment by stevk** [comment]
Fixed
