### ISSUE TITLE
Add an asset with two materials - one with specgloss and metalrough and another just metalrough

### ISSUE THREAD

**Issue by sbtron** [bghgary/glTF-Asset-Generator#268]
Ran into this with UnityglTF loader not being able to handle this use case.
Should be a valid asset with specgloss extensionused but not necessary that all materials in the asset also define the specgloss material.

**Comment by kcoley** [comment]
Putting info from issue #270 here:

- [ ] Specular Glossiness Extension Used and NOT used on mesh

- [ ] Specular Glossiness Extension Used, specular glossiness used on one mesh, metallic roughness on the other mesh.
