### ISSUE TITLE
Crash in wrapper setting material.PbrMetallicRoughness.BaseColorTexture.Index 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#27]
I'm encountering a crash. Running the build on my branch `stevk/mattextures` commit `52907e0 ` throws the exception.

I'm looking into if I'm passing in a bad combination of attributes, but it might be an issue with the wrapper.

**Comment by kcoley** [comment]
Okay, I'll check it out

**Comment by kcoley** [comment]
Looks like it was a typo on my part in the wrapper.  The indices for the metallic roughness texture were being assigned to the base color texture instead.  

PR created #28

**Comment by kcoley** [comment]
Merged
