### ISSUE TITLE
Add three additional Specular Glossiness Test Models

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#270]
- [ ] Specular Glossiness Extension Used and NOT used on mesh

- [x]  Specular Glossiness Extension Used, and used on mesh (already used (model 0) )

- [ ] Specular Glossiness Extension Used, specular glossiness used on one mesh, metallic roughness on the other mesh.

@stevk , could this be "addable" to your test generator for Specular Glossiness?

**Comment by stevk** [comment]
It should be, I'll take a look. I'm not sure about the first item on that list.

**Comment by kcoley** [comment]
Closing and moving info to #268.
