### ISSUE TITLE
Mesh Indices Model 15 has incorrect bytelength for buffer

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#280]

**Comment by kcoley** [comment]
Not sure if it's a bug in `ModelGroups` or `Runtime` layer.

**Comment by stevk** [comment]
I think I found the bug. Line 1328 of GLTFConverter.cs assumes int is the type. This also gives an incorrect bytelength for model 14.

`int byteLength = sizeof(int) * runtimeMeshPrimitive.Indices.Count();`

**Comment by kcoley** [comment]
Merged #282

**Comment by kcoley** [comment]
@stevk , let me know if this fixes the issue.

**Comment by stevk** [comment]
Your change fixed the issue
