### ISSUE TITLE
Build with vscode

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#317]
We want to build with Visual Studio Code, to better allow cross-platform development.

**Comment by stevk** [comment]
There isn't really anything to do here.

https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code

**Comment by kcoley** [comment]
I have been able to build this project with VS Code on Windows and Mac without having to make changes (VSCode installs all needed components).  This can probably be closed.

**Comment by stevk** [comment]
Yeah, it pretty much just works. I'm making a PR with the files it adds in order to build and debug. These get added automatically without much effort, but it should save us clicking "Yes" every time we start a new branch.

**Comment by kcoley** [comment]
Sounds good.  I'll give the PR a test with the change.  Testing on Mac.
