### ISSUE TITLE
Include machine-readable manifest file?

### ISSUE THREAD

**Issue by donmccurdy** [bghgary/glTF-Asset-Generator#325]
I see that there were [CSVs generated before](https://github.com/bghgary/glTF-Asset-Generator/issues/312), now replaced by the README in output directories.

I'm not sure how the old CSVs were used but it could be nice to have a machine-readable manifest somewhere (maybe CSV, maybe JSON...) listing all of the assets, the category, and the relative path to each. E.g. to set up a test page where the user can select an asset from the list to preview it, or preview several assets alongside one another.

**Comment by bghgary** [comment]
We talked about this offline before. I think it's a good idea to have a JSON file with the listing. It should be easy to generate.

**Comment by bghgary** [comment]
@stevk Can you take a look at implementing this?

**Comment by bghgary** [comment]
@donmccurdy How's this?

```json
{
    "folders": [
        {
            "folder": "Compatibility",
            "files": [
                "Compatibility_01.gltf",
                "Compatibility_02.gltf",
                "Compatibility_03.gltf",
                "Compatibility_04.gltf",
                "Compatibility_05.gltf"
            ]
        },
        {
            "folder": "Material",
            "files": [
                "Material_01.gltf",
                "Material_02.gltf",
                "Material_03.gltf",
                "Material_04.gltf"
            ]
        }
    ]
}
```

**Comment by donmccurdy** [comment]
Looks great! :)
