### ISSUE TITLE
Readme has broken links and needs to be updated

### ISSUE THREAD

**Issue by bghgary** [bghgary/glTF-Asset-Generator#331]

**Comment by stevk** [comment]
Which links are broken?

**Comment by bghgary** [comment]
Material Alphas at least. We need update that list whenever the output folder structure changes.

**Comment by stevk** [comment]
Oh! I see what you mean. It is the main GitHub readme that's broken. I thought you meant the readme for the individual model groups. I'll get a fix in.

https://github.com/bghgary/glTF-Asset-Generator/blob/master/README.md
