### ISSUE TITLE
PlayCanvas support

### ISSUE THREAD

**Issue by willeastcott** [bghgary/glTF-Asset-Generator#347]
[PlayCanvas' glTF loader](https://github.com/playcanvas/playcanvas-gltf) has largely been tested against the [glTF-Sample-Models repo](https://github.com/KhronosGroup/glTF-Sample-Models). I feel this repo would be a more rigorous test of the loader, so I thought I'd inquire as to how to get started.

I cloned the repo and opened the .sln, but Visual Studio 2017 Community Edition gives me:

![image](https://user-images.githubusercontent.com/697563/36355424-ce9a0542-1497-11e8-8717-8a756daa55e2.png)

Some advice on where to start would be great. Thanks!

**Comment by bghgary** [comment]
We will look into this. If you just want to test the available assets, use the generated files directly from the zipped files from the Releases or directly from the Output folder from master for the latest. There are README files for each folder that explains what each asset is supposed to do.

**Comment by willeastcott** [comment]
I certainly could do that. I downloaded the assets. I just wondered if there was already a mechanism to preview all the test results for a given engine. I notice there's already a Three.js subfolder.

**Comment by bghgary** [comment]
We are working on adding a live view link to each asset and adding a reference image. We will start with Babylon and Three for the live view. We will make it easy to add more engines afterwards.

**Comment by willeastcott** [comment]
OK, great. Let me know when you're ready to add PlayCanvas to the live view then. Thanks! 😄

**Comment by bghgary** [comment]
@willeastcott Please check out https://github.com/bghgary/glTF-Assets-Viewer and feel free to make a PR to add your engine to the list of viewers.

**Comment by bghgary** [comment]
For an example of how the viewer works, see any of the View links here: https://github.com/bghgary/glTF-Asset-Generator/tree/master/Output. For example, https://bghgary.github.io/glTF-Assets-Viewer/?manifest=https://raw.githubusercontent.com/bghgary/glTF-Asset-Generator/master/Output/Manifest.json&folder=6&model=2

Similar to #329, please do engine specific validation testing in each engine. Reopen this if you feel we need to do more with this.
