### ISSUE TITLE
Add reference image url to the json manifest

### ISSUE THREAD

**Issue by bghgary** [bghgary/glTF-Asset-Generator#348]
Once the reference images are generated and added to the readme files, it would be good if the json manifest is updated to include links to the reference images, one for each asset.

**Comment by stevk** [comment]
The reference images will have the same name as the assets (sans file type), so their url can be inferred from the manifest without any changes.

**Comment by bghgary** [comment]
I think it'll be better to be explicit, in case we want to break that contract later.
