### ISSUE TITLE
Image thumbnail names is no longer a thing we want to list in the manifest

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#372]
We might add it back in later...

**Comment by donmccurdy** [comment]
Sample, thumbnail, or both? (/what was the difference?) Some kind of reference is convenient for visual diffing although I understand if it's just not ready yet.

**Comment by bghgary** [comment]
We didn't want to lock down the schema for it yet as it's still in flux.

**Comment by stevk** [comment]
The thumbnail is a smaller version of the sample image. The thumbnail is what is visible while viewing a readme while the sample image is the full size image displayed when clicking one of the thumbnails.

We'll still have the images, they just won't be listed out in the manifest.

**Comment by donmccurdy** [comment]
I see, thanks. I'm hoping to use the sample images programmatically. If the names are consistent I guess I wouldn't need anything in `manifest.json` though.

**Comment by bghgary** [comment]
The names should be consistent, but I think we will eventually still put a path in the manifest to ensure it can be changed without breaking consumers.

**Comment by stevk** [comment]
Updated the title. We're only going to remove the thumbnails string, since that is more of an internal thing.
