### ISSUE TITLE
Material_AlphaMask issues

### ISSUE THREAD

**Issue by bghgary** [bghgary/glTF-Asset-Generator#374]
- [x] There is no model that tests the base color texture by itself.
- [x] The model with alphaCutoff 0.5 should not have 0.5 listed since it is the default.

We also used to have a model that resulted in the 0.8 alpha values of the texture to be cutoff, but this model doesn't exist anymore:
![image](https://user-images.githubusercontent.com/19158740/37316819-7bfb3a8e-261e-11e8-87a9-6be73896274c.png)
Not sure if we should bring this back or not.

**Comment by kcoley** [comment]
This has been updated via #388
