### ISSUE TITLE
Accessors with of 1-byte data are not aligned

### ISSUE THREAD

**Issue by lexaknyazev** [bghgary/glTF-Asset-Generator#384]
Each vertex must be aligned, i.e., buffer view for such accessors must have stride of 4.
```
Mesh_PrimitiveAttribute\Mesh_PrimitiveAttribute_01.gltf
    /meshes/0/primitives/0/attributes/TEXCOORD_0: Vertex attribute data must be aligned to 4-byte boundaries.

Mesh_PrimitiveVertexColor\Mesh_PrimitiveVertexColor_01.gltf
    /meshes/0/primitives/0/attributes/COLOR_0: Vertex attribute data must be aligned to 4-byte boundaries.

Mesh_PrimitiveVertexColor\Mesh_PrimitiveVertexColor_02.gltf
    /meshes/0/primitives/0/attributes/COLOR_0: Vertex attribute data must be aligned to 4-byte boundaries.
```

**Comment by bghgary** [comment]
Related: #368

**Comment by bghgary** [comment]
@lexaknyazev
We are going to fix this, but I'm curious why this doesn't cause an issue in any of the engines we've tested.

The spec states this:
> For performance and compatibility reasons, vertex attributes must be aligned to 4-byte boundaries inside `bufferView` (i.e., `accessor.byteOffset` and `bufferView.byteStride` must be multiples of 4).

What performance and compatibility reasons?

**Comment by bghgary** [comment]
Investigating more, it seems we are aligning the data to 4-byte boundaries.

**Comment by bghgary** [comment]
I think the code in question in the validator is this:
``` 
            if ((accessor.byteOffset != -1 &&
                    accessor.byteOffset.remainder(4) != 0) ||
                (accessor.elementLength.remainder(4) != 0 &&
                    accessor.bufferView != null &&
                    accessor.bufferView.byteStride == -1)) {
              context.addIssue(LinkError.meshPrimitiveAccessorUnaligned,
                  name: semantic);
            }
```

**Comment by lexaknyazev** [comment]
Buffer views don't have stride defined, so the validator infers `1` which is incorrect for vertex data.

**Comment by lexaknyazev** [comment]
> What performance and compatibility reasons?

Some GPUs (mostly mobile) may refuse to load unaligned data, it may lead to a runtime failure or in-driver data realignment.

**Comment by bghgary** [comment]
> Buffer views don't have stride defined, so the validator infers `1` which is incorrect for vertex data.

@lexaknyazev Can I open a bug on the validator and close this issue?

**Comment by lexaknyazev** [comment]
The issue is with models, not the validator.

**/Mesh_PrimitiveAttribute/Mesh_PrimitiveAttribute_01.gltf**
`/meshes/0/primitives/0/TEXCOORD_0` points to `/accessors/1`:
```json
{
  "bufferView": 1,
  "componentType": 5121,
  "normalized": true,
  "count": 4,
  "type": "VEC2",
  "name": "UV Accessor 0"
}
```
which points to `/bufferViews/1`
```json
{
  "buffer": 0,
  "byteOffset": 48,
  "byteLength": 8,
  "name": "Texture Coords 0"
}
```

So offsets for vertex data are:
```
stride is undefined, so stride = length of ubyte (1) * number of components (2) = 2
v0 - 0 (# vertex) * 2 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 48
v1 - 1 (# vertex) * 2 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 50 (not aligned)
v2 - 2 (# vertex) * 2 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 52
v3 - 3 (# vertex) * 2 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 54 (not aligned)
...
```

to fix this, buffer view needs to have stride of 4:
```
stride is explicitly 4
v0 - 0 (# vertex) * 4 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 48
v1 - 1 (# vertex) * 4 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 52
v2 - 2 (# vertex) * 4 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 56
v3 - 3 (# vertex) * 4 (stride) + 0 (offset in bufferView) + 48 (offset in buffer) = 60
...
```

**Comment by bghgary** [comment]
@lexaknyazev Ahh, I'm not sure why I didn't understand you before, but now I do. Thanks!

**Comment by bghgary** [comment]
@lexaknyazev I think we should clarify the spec. A few of us here misunderstood this statement.

> For performance and compatibility reasons, vertex attributes must be aligned to 4-byte boundaries inside bufferView (i.e., `accessor.byteOffset` and `bufferView.byteStride` must be multiples of 4).

This did not read as each element must be aligned to 4-byte boundaries to me. Perhaps this is better?

> For performance and compatibility reasons, each element of a vertex attribute must be aligned to 4-byte boundaries inside bufferView (i.e., `accessor.byteOffset` and `bufferView.byteStride` must be multiples of 4).

Possibly also add something similar to https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW7 for illustration purposes.

**Comment by lexaknyazev** [comment]
I agree with the spec update.

/cc @pjcozzi

**Comment by kcoley** [comment]
Should be resolved for the above models now.  Thanks for flagging @lexaknyazev !
