### ISSUE TITLE
the texture and figure structure can be changed to be simpler

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#392]
- [x] `Textures` should be extracted from the `Figures` directory (#391) 
- [ ] Below would be the new structure:
- Textures
  - Texture.png
- Figures
   FigureImage1.png
   FigureImage2.png
   - Renders
      - Image.#.png
      - Image.#.thumbnail.png 
   - Textures
      - Texture.thumbnail.png

**Comment by bghgary** [comment]
Okay with me.

**Comment by stevk** [comment]
I'm pretty sure this has already been fixed
