### ISSUE TITLE
Sampler is not allowing values to be assigned after it is created.

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#42]
I'm assigning values to the sampler, but those values are not showing up in the final model.

Look at the `stevk/texturetest `branch (I've commented out the other test sets for now, so only the sampler one will run)

In `Program.cs `:

- The sampler is declared on line 182
- Attributes are assigned to the sampler on lines 199-227

Opening the resulting glTF file shows a sampler that looks like the following for any combination of sampler attributes:
```
  "samplers": [
    {}
  ],
```

**Comment by kcoley** [comment]
I'll look into it

**Comment by kcoley** [comment]
PR created #43 

I think it's because the Sampler wrapper was using ints instead of the appropriate enums.

**Comment by kcoley** [comment]
Merged.
