### ISSUE TITLE
Material_AlphaMask_04 Sample doesn't match runtimes

### ISSUE THREAD

**Issue by najadojo** [bghgary/glTF-Asset-Generator#432]
The sample output [Material_AlphaMask_04.png](https://github.com/bghgary/glTF-Asset-Generator/blob/master/Output/Material_AlphaMask/Figures/SampleImages/Material_AlphaMask_04.png) doesn't match [runtime comparison](https://bghgary.github.io/glTF-Assets-Viewer/?manifest=https://raw.githubusercontent.com/bghgary/glTF-Asset-Generator/master/Output/Manifest.json&folder=5&model=4). I believe the runtimes are correct.

**Comment by bghgary** [comment]
> I believe the runtimes are correct.

+1 since the spec says this:
> If the alpha value is greater than or equal to the `alphaCutoff` value then it is rendered as fully opaque, otherwise, it is rendered as fully transparent.

And the `alphaCutoff` is `0.0` in this model which means it should be all opaque.

**Comment by stevk** [comment]
@kcoley I believe this is a bug with the screenshotGenerator.

**Comment by kcoley** [comment]
Probably so since the screenshot generator is running an older build of Babylon. I’ll update it to the latest npm.

**Comment by kcoley** [comment]
I just fixed the screenshot for [Material_AlphaMask_04.png](https://github.com/bghgary/glTF-Asset-Generator/blob/master/Output/Material_AlphaMask/Figures/SampleImages/Material_AlphaMask_04.png): 
https://github.com/bghgary/glTF-Asset-Generator/pull/433

I also updated the screenshot generator to BabylonJS version 3.3.0-alpha.6, which should generate the screenshot properly:
https://github.com/kcoley/screenshotGenerator/pull/1

Thanks for flagging @najadojo !

**Comment by kcoley** [comment]
@stevk you will probably need to do a pull and reinstall the npm packages to get the latest screenshot generator update on your end.  I updated the [README](https://github.com/kcoley/screenshotGenerator/blob/master/README.md) with the new packages.

**Comment by stevk** [comment]
@kcoley Thanks! I've updated my copy of the generator to the latest.
