### ISSUE TITLE
Flip Plane model so negative z is forward

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#84]
To be consistent with other web viewers, flip the plane model so that negative z is forward.

**Comment by stevk** [comment]
Isn't this an issue with Babylon?

**Comment by kcoley** [comment]
This also happens in Three.js and Cesium.  Currently it is not specified which direction is considered "front".  I'll try to find the thread and link it here from the glTF spec

**Comment by bghgary** [comment]
https://github.com/KhronosGroup/glTF/issues/1043

**Comment by kcoley** [comment]
Merged.
