### ISSUE TITLE
Add number formatting (file number fixed size) to the asset names to keep them in order on github

### ISSUE THREAD

**Issue by kcoley** [bghgary/glTF-Asset-Generator#97]

**Comment by stevk** [comment]
I don't think we really need this feature. We should have a discussion about it.

**Comment by bghgary** [comment]
It's not that important, but it should be super easy to implement.

**Comment by stevk** [comment]
Ah, I thought you were referring to numbering the folders. This makes way more sense.

**Comment by stevk** [comment]
fix pending
